### ISSUE TITLE
Still getting a terminal error on "grunt"

### ISSUE THREAD

**Issue by heathflohre** [happycog/templatestarter2016#14]
Running "sass:dev" (sass) task

> > Error: Invalid unit `medium`.
> >         on line 189 of components/include-media/dist/_include-media.scss
> > 
> > > > ```
> > > > @error $message;
> > > > ```
> > > > 
> > > >    ----^
> > > > Warning:  Use --force to continue.

**Comment by mrpaulphan** [comment]
Thanks @heathflohre Fixed.
