### ISSUE TITLE
Gulp version

### ISSUE THREAD

**Issue by caraya** [happycog/templatestarter2016#15]
Is there a Gulp version of the build file or is it Grunt only. I'm asking before deciding if I want to build my own  or not 🎱

**Comment by markhuot** [comment]
Sorry, @caraya, but there's no Gulp version. I used it on a project a while back and didn't see a noticeable improvement in memory usage or compile times. That said, if you wanted to PR a gulp branch I'd be happy to merge it in.

**Comment by caraya** [comment]
I figured as much. It has less to do with performance than with Gulp being my build workflow already and I'm not feeling the need to change to do use one tool. 

I'll put together a Gulp-based flow and submit a PR
