### ISSUE TITLE
Cannot get screen.css to compile

### ISSUE THREAD

**Issue by heathflohre** [happycog/templatestarter2016#7]
The Gruntfile is ignoring 'config.imports' because it's a partial. If it remove the underscore, it continually errors on sass variables.

**Comment by informa** [comment]
Agree.  There are lots of errors on undefined variables and _object.buttons.scss   typo. Would like to check this out once working.

**Comment by mrpaulphan** [comment]
@heathflohre  @informa We've updated this repo.

You should now be able to run this running the following commands
`npm install`
`bower install`
`grunt` to start 

Thanks for the feedback.

**Comment by heathflohre** [comment]
Getting new errors with _include-media.scss

Running "sass:dev" (sass) task

> > Error: Invalid unit `medium`.
> >         on line 189 of components/include-media/dist/_include-media.scss
> > 
> > > > ```
> > > > @error $message;
> > > > ```
> > > > 
> > > >    ----^
> > > > Warning:  Use --force to continue.
