### ISSUE TITLE
Undefined variables

### ISSUE THREAD

**Issue by heathflohre** [happycog/templatestarter2016#9]
$base-color: $green;
$pad: 20px;
$pad-double: $pad_2;
$pad-half: $pad/2;
$alpha-divider-color: $base-color;
$alpha-link-color: $base-color;
$alpha-link-color-hover: $base-color;
$button-color--alpha--inverse: $base-color;
$button-border-color--alpha--inverse: $base-color;
$button-color-hover--alpha--inverse: $base-color;
$button-border-color-hover--alpha--inverse: $base-color;
$button-background-color-hover--alpha--inverse: $base-color;
$button-color--alpha: $base-color;
$button-border-color--alpha: $base-color;
$button-color-hover--alpha: $base-color;
$button-border-color-hover--alpha: $base-color;
$button-background-color-hover--alpha: $base-color;
$button-background-color-hover--alpha--inverse: $base-color;
$button-background-color--beta: $base-color;
$button-background-color-hover--beta: $base-color;
$button-color-hover--beta: $base-color;
$color--alpha: $base-color;
$space: $pad;
$color--beta: $base-color;
$space-half: $space/2;
$space-and-half: $space+$space/2;
$space-double: $space_2;

**Comment by mrpaulphan** [comment]
Thank You @heathflohre. This has been updated
